// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP6H9f4nAotylbC1CoDPZ_LJBTPvxGJDg',
    appId: '1:350728688858:web:a5e40d042c199e732cc1e3',
    messagingSenderId: '350728688858',
    projectId: 'evans-flutter-notes',
    authDomain: 'evans-flutter-notes.firebaseapp.com',
    storageBucket: 'evans-flutter-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0IeV-AoDe0bKvZ1Mj_DqgZRTF7rZLQc',
    appId: '1:350728688858:android:1ed07588f1dfcf542cc1e3',
    messagingSenderId: '350728688858',
    projectId: 'evans-flutter-notes',
    storageBucket: 'evans-flutter-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOD0n-gAFgoNMssOfZdMN_Qmtc-QT61s',
    appId: '1:350728688858:ios:104f29f10f83f27a2cc1e3',
    messagingSenderId: '350728688858',
    projectId: 'evans-flutter-notes',
    storageBucket: 'evans-flutter-notes.appspot.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOD0n-gAFgoNMssOfZdMN_Qmtc-QT61s',
    appId: '1:350728688858:ios:104f29f10f83f27a2cc1e3',
    messagingSenderId: '350728688858',
    projectId: 'evans-flutter-notes',
    storageBucket: 'evans-flutter-notes.appspot.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP6H9f4nAotylbC1CoDPZ_LJBTPvxGJDg',
    appId: '1:350728688858:web:e08a68177a8ee5be2cc1e3',
    messagingSenderId: '350728688858',
    projectId: 'evans-flutter-notes',
    authDomain: 'evans-flutter-notes.firebaseapp.com',
    storageBucket: 'evans-flutter-notes.appspot.com',
  );

}